### ISSUE TITLE
Emails don't come in

### ISSUE THREAD

**Issue by alanthedon** [Gilwyad/mailnesia.com#16]
i haven't been recieving a password reset for my PSN Acc like I'm suppose to they came in before but not now

**Comment by PlayerXB** [comment]
me too i Got same problem, can we ask to fix this ASAP ?

**Comment by donricouga** [comment]
Ditto

**Comment by Gilwyad** [comment]
It's working again.

**Comment by Dioasmus** [comment]
I do not get a message. Mailnesia
