### ISSUE TITLE
Xbox One Account:  Cant get code to sign in to new device!

### ISSUE THREAD

**Issue by jimbothebimbo** [Gilwyad/mailnesia.com#17]
Mailnesia is down?  How do I get my Xbox Account back now?

**Comment by benbelden** [comment]
I am having the same problem. I found the following link:

http://account.live.com/proofs/MarkLost

You can enter an alternate contact method such as a phone number or new email and change the recovery method. The only catch is it looks like you have to wait 30 days before it will switch for security reasons. But if it works, it's better than not ever being able to sign in with the account.

**Comment by hellrokr** [comment]
i dont think it is xbox/outlook specific problem. Nothing is working at the moment.

**Comment by Gilwyad** [comment]
It's working again.
