### ISSUE TITLE
Can't access instagram

### ISSUE THREAD

**Issue by thebeastinreyes** [Gilwyad/mailnesia.com#18]
I used a mailnesia domain for my instagram, and now i've had to reset my password, but can't get the email because mailnesia is down. And has been down for nearly a week :/ Is it going to be gone forever?

edit: actually, the website i just used to check if it was down says its been down for 3 months--so again, is it gone forever??

**Comment by Gilwyad** [comment]
Dunno about instagram but mailnesia is up and running again
