### ISSUE TITLE
Site go down :(

### ISSUE THREAD

**Issue by moto2004** [Gilwyad/mailnesia.com#19]
Dear Bro,
Mailnesia site is very, very helpful for me with registration and others like that. 
Please check what is wrong. If you need any money for domain or server I can help with these. 
Regards.

**Comment by Gilwyad** [comment]
It is up and working again!

**Comment by moto2004** [comment]
Thank you!

**Comment by Deadooshka** [comment]
500 again

**Comment by moto2004** [comment]
Yes again stopped working :) 
Emails not arrive.
