### ISSUE TITLE
Order of the languages

### ISSUE THREAD

**Issue by Flucons** [Gilwyad/mailnesia.com#2]
It would be nice, if possible, place the languages in alphabetical order, both on the site and in Google Docs. Thank you.

**Comment by Gilwyad** [comment]
I'm not convinced that this is needed. There are only flags on the website, text only appears on hover. But anyway, how should we order? Something like this?

 - بالعربي
 - Bahasa Indonesia
 - Dalam bahasa melayu
 - V češtině
 - auf Deutsch
 - in English
 - En Español
 - En Español de Argentina
 - En Français
 - na hrvatskom
 - Italiano
 - latviešu valoda
 - magyarul
 - in het Nederlands
 - po polsku
 - Em Português do Brasil
 - português
 - на русском языке
 - v slovenščini
 - på svenska
 - suomi
 - 中文

1. I don't know where to put the languages with non-Latin characters: Arabic, Chinese, Russian
2. I think it should be sorted based on the language only, ignoring the "in" preposition. So where should Indonesian and Malay go, I and M or B and D? Maybe we could use the Wikipedia main page language order.

**Comment by Flucons** [comment]
Hello, thanks for answering.

Really is not something necessary, it would be just to follow a pattern.

I was thinking to use the ISO 639-1 two letter language code for sorting, to make things easier:

* ar >> Arabic
* cs >> Czech
* de >> German
* en >> English
* es >> Spanish
* es-ar >> Argentina Spanish
* fi >> Finnish
* fr >> French
* hr >> Croatian
* hu >> Hungarian
* id >> Indonesian
* it >> Italian
* lv >> Latvian
* ms >> Malay
* nl >> Dutch
* pl >> Polish
* pt >> Portuguese
* pt-br >> Brazilian Portuguese
* ru >> Russian
* sl >> Slovene
* sv >> Swedish
* zh >> Chinese

But, maybe, it would be better to order using the english name (making some adjustments):

* Arabic
* Chinese
* Croatian
* Czech
* Dutch
* English
* Finnish
* French
* German
* Hungarian
* Indonesian
* Italian
* Latvian
* Malay
* Polish
* Portuguese
* Brazilian Portuguese
* Russian
* Slovene
* Spanish
* Argentina Spanish
* Swedish
