### ISSUE TITLE
Problem with Microsoft verification codes

### ISSUE THREAD

**Issue by mistercloner** [Gilwyad/mailnesia.com#20]
We cannot receive Microsoft account verification codes on the mailbox. I even contacted the Microsoft support and told them this problem and they responded that the problem is not from their side and maybe Mailnesia system treats their email as spam or something else. Please fix this problem, this is my issue as well as a lot of other Microsoft users who used this mailbox as their security email like me.

**Comment by Dioasmus** [comment]
The same problem I have to fix it I do not get any message at all

**Comment by moto2004** [comment]
I have the same problem I can't login on my XBOX ACCOUNT with GTA5 becouse veryfication email doesn't arrive.

**Comment by Dioasmus** [comment]
And then that can be done. That they fix it please I can not verify my account I have everything there.
________________________________
De: moto2004 <notifications@github.com>
Enviado: jueves, 27 de abril de 2017 09:20:49 a. m.
Para: Gilwyad/mailnesia.com
Cc: Dioasmus; Manual
Asunto: Re: [Gilwyad/mailnesia.com] Problem with Microsoft verification codes (#20)


I have the same problem I can't login on my XBOX ACCOUNT with GTA5 becouse veryfication email doesn't arrive.

**Comment by Gilwyad** [comment]
I was able to add a Mailnesia email as a login alias to my Microsoft account, and the verification email arrived from Microsoft account team <account-security-noreply@accountprotection.microsoft.com> with subject 'Confirm your email address for your Microsoft account' ! What kind of verification doesn't arrive for you? Is it the other one, containing the numeric security code? I wasn't able to trigger that, only to my gmail address.
Note that you shouldn't use Mailnesia for any accounts you are not comfortable losing!
