### ISSUE TITLE
Thanks Gilwyad :)

### ISSUE THREAD

**Issue by Balantines** [Gilwyad/mailnesia.com#22]
Thanks ok good :)

**Comment by xboxnesia** [comment]
I join the request. Peter,  can  you fix it? I'll be very thankful!

**Comment by Dioasmus** [comment]
Pls Has to fix mailnesia. my account has important data and I need to verify the account since I do not get any message in mailnesia.

**Comment by moto2004** [comment]
Dear Peter, 

Again not work :(
Please fix it Bro.

Thanks.
