### ISSUE TITLE
Mailnesia inbox problem error 500 Internal Server  

### ISSUE THREAD

**Issue by moto2004** [Gilwyad/mailnesia.com#24]
Dear Gilwyad, 

Please check it, that is important for me. 
Now mailnesia not working :(

Remote host said: 500 Internal Server Error

THANKS !

**Comment by Gilwyad** [comment]
Must have been a temporary error. Emails are coming in currently. Could you be more specific? Otherwise will close this ticket.

**Comment by moto2004** [comment]
Hi Gilwyad - 500 Internal Server Error from about 10 hours. 
Can you check it ?
Thanks & Best Regards.
