### ISSUE TITLE
Mailnesia go down ?

### ISSUE THREAD

**Issue by Balantines** [Gilwyad/mailnesia.com#27]
Anyone have the same problem ?
Please help.

**Comment by xboxnesia** [comment]
Mailnesia  does not work 3 days already. This is a disaster!

**Comment by Balantines** [comment]
Yep, hope that Gilwyad can help :(

**Comment by xboxnesia** [comment]
It works!

**Comment by xboxnesia** [comment]
mailnesia.com does not work again. Fix it, please

**Comment by Gilwyad** [comment]
The server was down for 1 hour, 30 minutes and 0 seconds due to a
network issue at the hosting provider. The site came back online
automatically.
