### ISSUE TITLE
mailnesia.com does not work again.

### ISSUE THREAD

**Issue by xboxnesia** [Gilwyad/mailnesia.com#28]
mailnesia.com does not work again. Please fix it.

**Comment by Gilwyad** [comment]
It is working now.

**Comment by xboxnesia** [comment]
Thank you, but I still can not access your site. Maybe I should try through VPN?

**Comment by Balantines** [comment]
Hi Gilwyad, I also have problem, connection time out from about 2 days and still can't to connect. 
Can you help ? Thanks.

**Comment by Gilwyad** [comment]
There was an unknown problem, after I restarted the VPS it became unreachable in 30 minutes, but seems to be working now again.
