### ISSUE TITLE
Connection Time problem

### ISSUE THREAD

**Issue by Balantines** [Gilwyad/mailnesia.com#29]
Hi Gilwyad, I also have problem, connection time out from about 2 days and still can't to connect.
Can you help ? Thanks.

**Comment by grannite** [comment]
+1. Similar problem.
"This site can't be reached.
mailnesia.com took to long to respond.
ERR_CONNECTION_TIMED_OUT"

**Comment by Balantines** [comment]
Gilwyad please help still we can't use mainesia Err-Problem :( :(

**Comment by Balantines** [comment]
It is working now. 
Thank you Gilwyad, 
Is it any way to pay donation for mailnesia ?
You need any help with costs of servers, domain etc ?

**Comment by Gilwyad** [comment]
Should be OK now, please see issue #28 and #30 .
