### ISSUE TITLE
The server running Mailnesia will be decommissioned on 2018/01/10 - anyone still want to keep it going?

### ISSUE THREAD

**Issue by Gilwyad** [Gilwyad/mailnesia.com#30]
I got word from the hosting company Prometeus that the server running Mailnesia will be decommissioned on 2018/01/10. I have to relocate the service to a different server/hosting provider. Problem is, I'm getting tired working on this project which is just a hobby for me, takes a lot of time and gives absolutely no reward/benefit/income. Possible alternatives:

- the site goes down permanently on 2018/01/10
- I relocate to a different provider and
  - introduce advertisments
  - and/or introduce donations with bitcoin, paypal

Any ideas?

**Comment by mapas2002** [comment]
The emails are not coming in about 3 days, are you in trouble?

**Comment by mapas2002** [comment]
no one to answer ??

**Comment by mapas2002** [comment]
Will I have to abandon mailnesia?

**Comment by Margamel2** [comment]
keep it going

**Comment by Gilwyad** [comment]
I added donation information to the [contact](https://mailnesia.com/contact.html) page.
