### ISSUE TITLE
I'm not getting any emails

### ISSUE THREAD

**Issue by Margamel2** [Gilwyad/mailnesia.com#32]

**Comment by mapas2002** [comment]
It has been 4 days that the e-mail is not arriving and when it arrives you can not do more to confirm the e-mail because the deadline has expired ..

**Comment by mapas2002** [comment]
Very good the mailnesia but unfortunately the developer does not answer our questions leaving users aside

**Comment by xboxnesia** [comment]
Same problem.

**Comment by Gilwyad** [comment]
Looks like the email server  is very overloaded. There are simply too many imcoming emails. Not sure if I can do anything with this. Just moved to a faster server.

**Comment by mapas2002** [comment]
One opinion, delete all the emails that are on the server to see if it solves the problem, is currently scheduled to self-delete the emails from a period of time? 
I had to go back to using yopmail, which sucks because of recapcha

**Comment by mapas2002** [comment]
Start deleting all emails that currently exist in the database

**Comment by mapas2002** [comment]
I use mailnesia 5 months ago and I love mailnesia !! Unfortunately last week ...

**Comment by Balantines** [comment]
Gilwyad is there any chance to mailnesia work correctly ?
Please ;) I am also waiting for donate button Bro.

**Comment by Gilwyad** [comment]
The problem is not the database but the rate of incoming emails. The mail server uses 100% CPU all the time, it just cannot keep up. I suspect the most CPU intensive part is parsing the whole email body to find all links to click, so I temporarily disabled this clicker to see if it helps. So far it seems it does. I will try to figure out a way to make it less CPU intensive.

**Comment by Gilwyad** [comment]
I deployed a fix and the clicker is turned on again. Feel free to reopen if the issue persists.

**Comment by Gilwyad** [comment]
@Balantines I added donation information to the contact page :)
