### ISSUE TITLE
new keyword

### ISSUE THREAD

**Issue by ghost** [Gilwyad/mailnesia.com#39]
hello, please add "email_validation" to the keywords

**Comment by Gilwyad** [comment]
This should already work according to this regex:

https://github.com/Gilwyad/mailnesia.com/blob/fc34dd6300e07dd3d3f0e8234b90a68db4dfeb73/lib/Mailnesia/Email.pm#L56

It matches any word starting with 'validat', continuing with e or i, for example validation.
