### ISSUE TITLE
mailnesia doesn't working right now

### ISSUE THREAD

**Issue by Balantines** [Gilwyad/mailnesia.com#41]
Hello, 

ERR_CONNECTION_TIMED_OUT

Gilwyad can you help fast for 100 USD donation ? ;)

**Comment by Mulaiman** [comment]
Same here.
Is there a fix?

**Comment by xboxnesia** [comment]
Gilwyad, help, please!

**Comment by Balantines** [comment]
DDOS attack guys.

**Comment by Mulaiman** [comment]
Any news? @Gilwyad

**Comment by Balantines** [comment]
Like you see no information :( 

Maybe you can offer more donation ?
I think that server isn't cheap and free. 

For me 100 USD when mailnesia come back. 
Paypal or btc.

**Comment by Mulaiman** [comment]
When the page is running again, he can expect a donation from me as well. But first, I'd like a statement from the owner.

**Comment by Balantines** [comment]
Good how many ?

**Comment by Mulaiman** [comment]
Let's see. Some mBTC

**Comment by Gilwyad** [comment]
Seems to be up now, please see http://mailnesia.com/contact.html for the
donation ;)

**Comment by Balantines** [comment]
Thanks Bro, 
100 USD send to you.
Have nice day :)

Also please leave here live contact to you for faster help in future :)

**Comment by Mulaiman** [comment]
I'll keep my promise too and donate.
Thanks @all

**Comment by Gilwyad** [comment]
I received the 100 from Zedd! Thank you!

**Comment by Balantines** [comment]
Hi @Gilwyad again same problem.
Can you help ?

**Comment by kdcz** [comment]
Seems down, can you put it up again and I'll donate 100 USD aswell thank you!

**Comment by Kam1kaze621** [comment]
Yes mailnesia is actually down.Hopefully GIlwyad's gonna fix it asap.

**Comment by Kam1kaze621** [comment]
@Gilwyad Peter,we need your help !

**Comment by Gilwyad** [comment]
It's up now guys

**Comment by Kam1kaze621** [comment]
Thanks a lot sir @Gilwyad

Le dim. 27 oct. 2019 à 16:54, Peter Baranyi <notifications@github.com> a
écrit :

**Comment by Balantines** [comment]
@Gilwyad 

PSame problem come back. 
Can you help us please.

**Comment by Balantines** [comment]
@Gilwyad Peter,we need your help ! :)

**Comment by Gilwyad** [comment]
The VPS powers down sometimes for unknown reasons and I have to log in to the hosting provider's client area and manually start it.

**Comment by Tegga27** [comment]
Mailnesia can access but, receive email not work

**Comment by Mulaiman** [comment]
@Gilwyad please start it again.

**Comment by Sockenbarsch** [comment]
@Gilwyad pleas start it again

**Comment by Sockenbarsch** [comment]
@Gilwyad please start it again

**Comment by Gilwyad** [comment]
I started it, here are some details: https://blog.mailnesia.com/post/190013581704/downtime
