### ISSUE TITLE
Mailnesia not work

### ISSUE THREAD

**Issue by Tegga27** [Gilwyad/mailnesia.com#43]
@Gilwyad

**Comment by Balantines** [comment]
Yes still not working :(

**Comment by Balantines** [comment]
@Gilwyad where are you Bro :)

**Comment by Mulaiman** [comment]
Seems to happen at the end of every month...
@Gilwyad please help, refresh your dns client or so

**Comment by Mulaiman** [comment]
Thanks, works agaiin

**Comment by Sockenbarsch** [comment]
@Gilwyad Please help, Mailnesia doesn't work. Can you start it again?

**Comment by Gilwyad** [comment]
I started it, here are some details: https://blog.mailnesia.com/post/190013581704/downtime
