### ISSUE TITLE
Mailnesia doesn't Work

### ISSUE THREAD

**Issue by Sockenbarsch** [Gilwyad/mailnesia.com#44]
Help the Germans please. Can you start the page again?

**Comment by Balantines** [comment]
@Gilwyad can you check it ?

**Comment by Balantines** [comment]
@Gilwyad  again same problem :) 
Thanks for last time fix.

**Comment by Gilwyad** [comment]
I started it, here are some details: https://blog.mailnesia.com/post/190013581704/downtime
