### ISSUE TITLE
No source IP in original mail, can't report them on spamcop

### ISSUE THREAD

**Issue by iripu** [Gilwyad/mailnesia.com#54]
I report spams to spamcop.net. It works on spams sent to gmail and others. But, copy pasting original mail from mailnesia to spamcop, it does not work, can't report.

Spamcop says there is no source IP address in the original mail.
![image](https://user-images.githubusercontent.com/11015012/210128022-e1f8ff5d-fd93-4366-9c95-c911df4d75e8.png)

The header is not sufficient like below:
![image](https://user-images.githubusercontent.com/11015012/210128038-e1e409f8-ed09-4166-ad04-a947f1042a46.png)

Is there any way to fix this? I am asking because reporting on spamcop works and spams are blocked by source mail server.

**Comment by Gilwyad** [comment]
Mailnesia stores the emails with all headers exactly as received. Do you
think it should add a header such as

Received: from hostname ([Ip])

Where the values are of the machine that sent the email?

**Comment by iripu** [comment]
Thanks for the reply.

I am not sure whether gmail and others add the IP themselves to the header or not. Here is an example of part of the header that has the IP (44.192.35.18), which is detected by spamcop. This one is not a spam, I just tested where spamcop got the IP from. It originally came as a reply from contact@365scores.com.

![email header](https://user-images.githubusercontent.com/11015012/210166658-34defd1b-c761-4156-8ed6-3f849a8db246.png)

If possible, yes, adding IPs would be great to report spams and reducing them.

**Comment by iripu** [comment]
Is it possible to fix this?

![image](https://user-images.githubusercontent.com/11015012/216263905-a031beba-6830-4b1c-a6b0-4c5c9d10fb07.png)

**Comment by Gilwyad** [comment]
Yes, I implemented and deployed this. Here's an example header that now is added:

    Received: FROM mail-pj1-f41.google.com [ 209.85.216.41 ] BY mailnesia.com ; Tue, 07 Feb 2023 23:21:11 +0000

Please test it and let me know if it works with Spamcop or if I should modify something.
