### ISSUE TITLE
Issue with receiving emails from Instagram

### ISSUE THREAD

**Issue by MagnetApe** [Gilwyad/mailnesia.com#60]
Hey, Im trying to recover an Instagram password on the email matthewwood205@mailnesia.com

But I'm not able to receive any emails from Instagram. It says the email was sent but I don't find it in my post box

It's not an issue of Instagram since other emails worked for me, it's only with this email. Is there a way to fix this

Kind regards

**Comment by Gilwyad** [comment]
Mailnesia does not block Instagram but Mailnesia could be blocked by Instagram - cannot do anything about it.
