### ISSUE TITLE
Mailnesia down nearly 12 hrs

### ISSUE THREAD

**Issue by dangbh271** [Gilwyad/mailnesia.com#64]
Hi Dilwyad,

Mailnesia.com down nearly 12hrs. Could you fix it sir ?

**Comment by itasterix** [comment]
same issue

**Comment by klitzy1** [comment]
it's almost 3 days down guys, do we have any news about Peter and mailnesia of what happened?

**Comment by Gilwyad** [comment]
Yes sorry about that, it was due to overload caused by bots most probably.
